### ISSUE TITLE
wxAuiNotebook - behavior differences when deleting tabs

### ISSUE THREAD

**Issue by robertop** [nhold/wxWidgets#34] opened 2014-03-21 05:49 UTC
Run the aui sample
close the tab "wxTextCtrl 5"
The notebook displays the first page.

On master, the aui sample behaves differently.  When you close the tab "wxTextCtrl 5" the next tab (wxTextCtrl 6) is shown.

Tested commit  0e3924e0db169be04e6d843d345c57aaf1ca5ee9
Ubuntu linux 12.04

**Comment by ghost** [comment] 2014-05-09 08:59
I reproduced this problem successfully. Trying to fix it.

**Comment by ghost** [comment] 2014-05-09 16:05
This should be fixed by my latest pull request

**Comment by nhold** [comment] 2014-05-12 12:15
Works for me.

**Closed as completed by nhold** 2014-05-12 12:15 UTC
Labels: bug
