### ISSUE TITLE
wxAuiNotebookEvent - EVT_AUINOTEBOOK_TAB_RIGHT_UP not being propagated

### ISSUE THREAD

**Issue by robertop** [nhold/wxWidgets#35] opened 2014-03-21 07:01 UTC
The right up event (and maybe others?) seems to not be propagated correctly. The event is propagated when the click happens outside of the tabs, instead of propagating when a tab was clicked.
1. Patch the aui sample with the patch below
2. compile and run the aui sample
3. With the aui sample opened, hover over a notebook tab and click the right mouse button. Nothing happens.
4. Now hover over the notebook on an empty space to the right of the tabs.  click the right mouse button. A menu appears.

If you apply the patch to master and run the aui sample, when you click the right mouse button on a tab the menu appears.

Tested on 0e3924e0db169be04e6d843d345c57aaf1ca5ee9
Ubuntu linux 12.04

```
diff --git a/samples/aui/auidemo.cpp b/samples/aui/auidemo.cpp
index 186480e..0933dc5 100644
--- a/samples/aui/auidemo.cpp
+++ b/samples/aui/auidemo.cpp
@@ -60,6 +60,21 @@ class wxAuiNotebook;

 class wxSizeReportCtrl;

+// to test tab click functionality
+class MyNotebook : public wxAuiNotebook 
+{
+
+public:
+
+    MyNotebook(wxWindow* parent, int id, wxPoint point, wxSize size, long style);
+
+private:
+
+    void OnNotebookTabRightUp(wxAuiNotebookEvent& evt);
+
+    DECLARE_EVENT_TABLE()
+};
+
 // -- frame --

 class MyFrame : public wxFrame
@@ -683,6 +698,9 @@ BEGIN_EVENT_TABLE(MyFrame, wxFrame)
     EVT_AUINOTEBOOK_PAGE_CLOSED(wxID_ANY, MyFrame::OnNotebookPageClosed)
 END_EVENT_TABLE()

+BEGIN_EVENT_TABLE(MyNotebook, wxAuiNotebook)
+    EVT_AUINOTEBOOK_TAB_RIGHT_UP(wxID_ANY, MyNotebook::OnNotebookTabRightUp)
+END_EVENT_TABLE()

 MyFrame::MyFrame(wxWindow* parent,
                  wxWindowID id,
@@ -1710,7 +1728,7 @@ wxAuiNotebook* MyFrame::CreateNotebook()
    // create the notebook off-window to avoid flicker
    wxSize client_size = GetClientSize();

-   wxAuiNotebook* ctrl = new wxAuiNotebook(this, wxID_ANY,
+   wxAuiNotebook* ctrl = new MyNotebook(this, wxID_ANY,
                                     wxPoint(client_size.x, client_size.y),
                                     wxSize(430,200),
                                     m_notebook_style);
@@ -1833,3 +1851,17 @@ wxString MyFrame::GetIntroText()

     return wxString::FromAscii(text);
 }
+
+MyNotebook::MyNotebook(wxWindow* parent, int id, wxPoint point, wxSize size, long style)
+: wxAuiNotebook(parent, id, point, size, style)
+{
+    
+}
+
+void MyNotebook::OnNotebookTabRightUp(wxAuiNotebookEvent& WXUNUSED(evt))
+{
+   wxMenu menu;
+   menu.Append(wxID_ANY, wxT("Close All Tabs"));
+   menu.Append(wxID_ANY, wxT("Close This Tab"));
+   PopupMenu(&menu);
+}
```

**Comment by ghost** [comment] 2014-05-09 16:11
Thanks for the test case. I now see where the problem is. I will fix it quickly now

**Comment by ghost** [comment] 2014-05-09 16:33
It should be fixed now :)

**Closed as completed** 2014-05-12 12:15 UTC
Labels: bug
